name = "BitLogic"
uuid = "1de7c230-a48e-4064-9941-ea1b8c0be278"
authors = ["Daniel Schwarzenbach"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
